[project]
name = "mcp-canteen-server"
version = "0.1.1"
description = "职工餐厅就餐人数查询MCP服务器"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
